{
 "title": "xchain",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "交易TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{job=\"xchain\",grpc_method=~\"PostTx|PreExecWithSelectUTXO|BatchPostTx\"}[10s])) by (instance, grpc_method)"
    }
   ]
  },
  {
   "title": "交易耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.80,sum(rate(grpc_server_handling_seconds_bucket{job=\"xchain\",grpc_method=~\"PostTx|PreExecWithSelectUTXO|BatchPostTx\"}[10s])) by (instance,grpc_method,le))"
    }
   ]
  },
  {
   "title": "处理广播消息错误率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xuperos_common_call_method_total{job=\"xchain\",method=\"SubmitTx\",code!=\"OK\"}[10s])) by (instance,method)\n / \nsum(rate(xuperos_common_call_method_total{job=\"xchain\",method=\"SubmitTx\"}[10s])) by (instance,method)\n * 100.0"
    }
   ]
  },
  {
   "title": "tx_per_block",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(xuperos_ledger_confirmed_tx_total[10s])/rate(xuperos_ledger_height_total[10s])"
    }
   ]
  },
  {
   "title": "高度",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "string" }
   ],
   "targets": [
    { "expr": "xuperos_ledger_height_total" }
   ]
  },
  {
   "title": "出块率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(xuperos_ledger_height_total[30s])"
    }
   ]
  },
  {
   "title": "出块耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(xuperos_common_call_method_seconds_sum{module=\"miner\"}[10s]) / rate(xuperos_common_call_method_seconds_count{module=\"miner\"}[10s])"
    }
   ]
  },
  {
   "title": "块追耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(xuperos_common_call_method_seconds_sum{module=\"sync\"}[10s]) / rate(xuperos_common_call_method_seconds_count{module=\"sync\"}[10s])"
    }
   ]
  },
  {
   "title": "未确认交易量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "xuperos_state_unconfirmed_tx_gauge"
    }
   ]
  },
  {
   "title": "上链交易量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xuperos_ledger_confirmed_tx_total{job=\"xchain\"}[10s])) by (instance, bcname)"
    }
   ]
  },
  {
   "title": "发送网络消息TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xuperos_network_msg_send_total{job=\"xchain\"}[10s])) by (instance,message)"
    }
   ]
  },
  {
   "title": "接收网络消息TPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xuperos_network_msg_received_total{job=\"xchain\"}[10s])) by (instance,message)"
    }
   ]
  },
  {
   "title": "发送消息字节量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xuperos_network_msg_send_bytes{job=\"xchain\"}[30s])) by (instance,message)"
    }
   ]
  },
  {
   "title": "接收消息字节量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xuperos_network_msg_received_bytes{job=\"xchain\"}[10s])) by (instance,message)"
    }
   ]
  },
  {
   "title": "发送消息耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(xuperos_network_client_handled_seconds_bucket[10s])) by (instance,message,le))"
    }
   ]
  },
  {
   "title": "接收消息耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(xuperos_network_server_handled_seconds_bucket[10s])) by (instance,message,le))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"xchain\"}[30s])"
    }
   ]
  },
  {
   "title": "MEM",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"xchain\"}"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"xchain\"}"
    }
   ]
  },
  {
   "title": "open_fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{job=\"xchain\"}"
    }
   ]
  },
  {
   "title": "levelDB请求量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xuperos_common_call_method_total{module=\"levelDB\"}[10s])) by (instance, method)"
    }
   ]
  },
  {
   "title": "levelDB bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(rate(xuperos_common_handle_bytes[10s])) by (method, handle, instance)"
    }
   ]
  },
  {
   "title": "平均响应时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(grpc_server_handling_seconds_sum{grpc_method=~\"PostTx|PreExecWithSelectUTXO\"}[10s])\n/\nrate(grpc_server_handling_seconds_count{grpc_method=~\"PostTx|PreExecWithSelectUTXO\"}[10s])"
    }
   ]
  },
  {
   "title": "广播消息处理耗时",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(xuperos_common_call_method_seconds_bucket{method=~\"SENDBLOCK|POSTTX\"}[1h])) by (instance,method,le))"
    }
   ]
  },
  {
   "title": "并发访问量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "xuperos_common_concurrent_requests_total"
    }
   ]
  },
  {
   "title": "PostTx耗时细分项",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(xuperos_common_call_method_seconds_bucket{method=~\"doTxLock|doTxInternal|batchWrite|cacheFiller|xmodelDoTx|ImmediateVerifyTx\"}[10s])) by (instance,method,le))"
    },
    {
     "expr": "histogram_quantile(0.85, sum(rate(xuperos_common_call_method_seconds_bucket{module=\"posttx\"}[10s])) by (instance,method,le))"
    }
   ]
  }
 ]
}